### ISSUE TITLE
Error:  "Unable to find the chunk requested because its a super chunk" on quokka file loading.

### ISSUE THREAD

**Issue by RobinDavid** [quarkslab/quokka#25]
Hi !

I am encountering an issue when load quokka files generated from kernel modules. The export seems to be performed correctly but the loading fails with the exception:

> Unable to find the chunk requested because its a super chunk

Here is a simple modules to reproduce: [pktflow.ko.zip](https://github.com/quarkslab/quokka/files/14508919/pktflow.ko.zip)

```python
from quokka import Program

p = Program("pktflow.ko.Quokka", "pktflow.ko")
```

Tested with:
* IDA Pro 8.2
* Quokka: 0.5.4

**Comment by patacca** [comment]
It seems that the very first chunk that we encounter is **always** treated as a fake chunk. Nobody has ever noticed probably because in normal conditions Quokka is still able to export the function correctly and from the python api everything is still accessible (call graph, instructions, etc...).

In this case IDA for some ~~unexplainable~~ reasons creates different blocks for the `fcacheStatus` function (that is the function at address `0`) without having jumps between the blocks. Quokka identifies two blocks (even though IDA shows 3) but fails to resolve the edge between them (because there is no code reference from one to the other), this leads the python API to believe that the function is in fact a `SuperChunk` that ultimately causes a chain reaction making impossible to access the attributes of the function `fcacheStatus`.

I will fix it asap
